# Generated by Django 5.2 on 2025-04-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_teachersubject'),
        ('users', '0002_remove_teacher_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='section',
            field=models.ManyToManyField(blank=True, related_name='section_teachers', through='api.TeacherSubject', to='api.section'),
        ),
    ]
