# Generated by Django 5.2 on 2025-04-21 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_teachersubject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='total_students',
        ),
        migrations.RemoveField(
            model_name='studentclass',
            name='total_students',
        ),
    ]
