# Generated by Django 5.2 on 2025-04-11 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
        migrations.AddField(
            model_name='section',
            name='incharge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_sections', to='users.teacher'),
        ),
        migrations.AddField(
            model_name='result',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_results', to='api.section'),
        ),
        migrations.AddField(
            model_name='section',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_sections', to='api.studentclass'),
        ),
        migrations.AddField(
            model_name='result',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_results', to='api.studentclass'),
        ),
        migrations.AddField(
            model_name='result',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_results', to='api.subject'),
        ),
    ]
